#.travis.yml

language: node_js
node_js:
  - "8.5.0"
sudo: required
dist: trusty
addons:
  chrome: stable
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
  - npm install -g firebase-tools
  - npm install -g @angular/cli

stages:
  - name: test
    if: branch != master
  - name: deploystaging
    if: branch = master

jobs:
  include:
  - stage: test
    script:
      - ng test
      - npm run-script coverage
  - stage: deploystaging
    script:
      - ng test
      - npm run-script lint
      - npm run-script coverage
      - npm run-script build-dev
    after_success:
      - firebase deploy -P staging --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change