#.travis.yml

language: node_js
node_js:
  - "8.5.0"

stages:
  - test
  - deploystaging
  - name: deployprod
    if: branch = master

jobs:
  include:
  - stage: test
    before_script:
      - npm install -g firebase-tools
      - npm install -g @angular/cli
    script:
      - ng test
  - stage: deploystaging
    before_script:
      - npm install -g firebase-tools
      - npm install -g @angular/cli
    script:
      - npm run-script build-dev
    after_success:
      - firebase deploy -P staging --token $FIREBASE_TOKEN
  - stage: deployprod
    before_script:
      - npm install -g firebase-tools
      - npm install -g @angular/cli
    script:
      - npm run-script build
    after_success:
      - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change